### ISSUE TITLE
Zakładka "Moje konto"

### ISSUE THREAD

**Issue by karolinakosowska** [Karos64/karos64.github.io#19]
- po zalogowaniu i kliknięciu ikonki konta
- możliwość wyświetlenia danych
- możliwość przejrzenia ogłoszeń wystawionych - zakładka "Aktywne"
- możliwość usuwania wystawionych ogłoszeń 
- dla schronisk - możliwość ponownego wystawienia ogłoszenia (po zatwierdzeniu adopcji znika ze strony głównej, na koncie widoczne jest w zakładce "Nieaktywne", ale nie mamy pewności, czy do adopcji dojdzie i żeby nie trzeba było od nowa podawać danych)
- zakładka "Nieaktywne" również dla użytkowników - tam są zwierzęta, które zostały adoptowane
- możliwość przejrzenia zwierząt adoptowanych - zakładka "Adoptowane" (nie zabraniamy schroniskom adoptować zwierząt więc wygląd konta identyczny dla schronisk i użytkowników, tylko inne dane)
- możliwość wylogowania

**Comment by Karos64** [comment]
done
