### ISSUE TITLE
Strona zwierzęcia

### ISSUE THREAD

**Issue by karolinakosowska** [Karos64/karos64.github.io#20]
- naprawić responsywność
- inny opis dla schroniska, inny dla użytkownika
schronisko:
```
imię, zwierzę, płeć, wiek, rodowód, schronisko
```
osoba fizyczna:
```
imię, zwierzę, płeć, wiek, rodowód, miasto, użytkownik (imię+nazwisko), email
```
- dla ogłoszeń użytkownika nie ma przycisku "Adoptuj" ani kalendarza - użytkownik na własną rękę się kontaktuje
- dopasowane zdjęcia, imiona do płci, itd.
- nad kalendarzem napis "Wybierz dzień adopcji"
- pod kalendarzem obowiązkowy checkbox do zaznaczenia w stylu "Potwierdzam adopcję i zobowiązuję stawić się osobiście w wybranym wyżej terminie w placówce schroniska w celu adopcji zwierzęcia"
- działanie kalendarza - brak możliwości zaznaczenia starej daty, możliwość zmiany miesiąca, możliwość zatwierdzenia
- dopisanie do przycisku "Zatwierdź" strony potwierdzającej albo wymagającej zalogowania

**Comment by Karos64** [comment]
Działa wszystko oprócz możliwości zmiany miesiąca, możliwość zatwierdzenia, dopisanie do przycisku "Zatwierdź" strony potwierdzającej albo wymagającej zalogowania

**Comment by Karos64** [comment]
Działa scrollowanie kalendarza

**Comment by Karos64** [comment]
I guess this is done, zostały tylko jsony ale to Jonasz załatwi
