### ISSUE TITLE
Filtry

### ISSUE THREAD

**Issue by karolinakosowska** [Karos64/karos64.github.io#21]
- w filtrze "Schronisko" trzeba dodać opcję wyboru schronisk i osoby prywatnej, więc nie może się nazywać "Schronisko" tylko np. "Właściciel"
- Dodać tworzenie filtrów na podstawie JSON'ów
- wyszukiwanie musi być niewrażliwe na rozmiar liter
- dodanie możliwości specyfikowania właściciela bez konieczności wybierania miasta
- działający Enter

**Comment by ArkoJano** [comment]
bruh, ale to teraz trzeba zrobić dodawanie właścicieli do schronisk
To na pewno dobry pomysł żeby to łączyć? Wymiesza się nieźle

**Comment by karolinakosowska** [comment]
I mean Właściciel lista: dognohome, schronisko2, schronisko3, osoba prywatna
