### ISSUE TITLE
Zakładka "Wspomóż"

### ISSUE THREAD

**Issue by karolinakosowska** [Karos64/karos64.github.io#24]
- na początku żaden przycisk płatności niezaznaczony
- naprawić responsywność
- fajnie gdyby formularze miały format podobny do mojego, głównie chodzi o czcionki
- na stronie płatności trzeba albo po kilku sekundach przekierować do strony "successful_donation" albo zrobić do tego przycisk
- upiększyć trochę stronę płatności
- usunąć dwukropki

**Comment by Kajiysor** [comment]
> * na początku żaden przycisk płatności niezaznaczony

It's not a bug, it's a feature


> * upiększyć trochę stronę płatności

Nie wiem po co w sumie bo strona płatności nie znajduje się po naszej stronie tylko po stronie serwisu, który wybrał użytkownik. Można ewentualnie po prostu wycentrować napis i dać przycisk "Powrót do strony".

**Comment by karolinakosowska** [comment]
O to właśnie chodzi w upiększyć, zobaczymy co powie jak to zobaczy we wtorek
