### ISSUE TITLE
"Baza danych"

### ISSUE THREAD

**Issue by karolinakosowska** [Karos64/karos64.github.io#26]
- ogłoszenia po dodaniu w "Oddaj" zapisywane do "bazy" w odpowiednim formacie - 
od osób prywatnych
```
"owner": "user", 
 "shelter": ,
 "city": "Kraków",
 "user": "Jan Kowalski",
 "email": "jankowalski@gmail.com",
 "number": "123456789",
```
od schronisk:
```
"owner": "shelter", 
 "shelter": (tutaj trzeba nazwę i cały adres skleić w takiego stringa) "YetAnotherShelter - Opolska 28, 30-437 Kraków",
 "city": "Kraków",
 "user": ,
 "email": ,
 "number": ,
```
- ogłoszenia usuwane po adopcji ze SCHRONISKA (przenoszone z active do inactive w pliku schroniska) ale ciągle możliwe do przywrócenia w Moje konto (z inactive do active)
- możliwość usuwania ogłoszeń w Moje konto
- zapisywanie danych schronisk i użytkowników tworzących konta
- dodawanie miast, których nie ma w bazie, ale użytkownik, który wystawił ogłoszenie tam mieszka - żeby można było filtrować też

**Comment by Karos64** [comment]
Trzeba ogarnąć wygląd strony "Moje konto", wtedy można zacząć myśleć nad tym żeby to działalo - ktoś chętny? @Kajiysor @ArkoJano @karolinakosowska

**Comment by Karos64** [comment]
done oprócz tych miast, co teraz? implementujemy to?

**Comment by Karos64** [comment]
done i guess
